apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: chameleon
spec:
  selector:
    matchLabels:
      app: chameleon
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: chameleon
    spec:
      containers:
      - name: chameleonserver
        image: emdoyle/chameleon:latest
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: chameleonsecrets
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: chameleonsecrets
              key: DB_PASSWORD
        - name: COOKIE_SECRET
          valueFrom:
            secretKeyRef:
              name: chameleonsecrets
              key: COOKIE_SECRET
        envFrom:
        - configMapRef:
            name: {{ .Release.Name }}
        imagePullPolicy: Always
        ports:
        - containerPort: 8888
          name: tcp-chameleon
        readinessProbe:
          tcpSocket:
            port: 8888
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8888
          initialDelaySeconds: 15
          periodSeconds: 10
