"""Add final_vote to VotePhase

Revision ID: 5a18b7b14096
Revises: 27425e1cbb40
Create Date: 2020-03-28 20:16:08.071885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5a18b7b14096"
down_revision = "27425e1cbb40"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("vote_phases", sa.Column("final_vote", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("vote_phases", "final_vote")
    # ### end Alembic commands ###
